version: '1'

services:
    flask-app:
        container_name: double_sql
        build: double_sql
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./double_sql:/double_sql
        networks:
            - backend

    mysql-db:
        container_name: mysql-db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: iitb_ctf
        ports:
            - '3308:3306'
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    app:
    database:
